package com.muspelheim.httpbucket.generator;

import org.springframework.ws.soap.SoapMessage;

import com.muspelheim.httpbucket.generator.exception.ResponseCouldNotBeGeneratedException;

public interface SoapResponseGenerator {

	/**
	 * Delegates the response generation to the given script
	 * 
	 * @param scriptName
	 * @param request
	 * @return
	 * 		The response generated by the given script  
	 * @throws ResponseCouldNotBeGeneratedException
	 */
	String generateSoapResponse(String scriptName, SoapMessage request) throws ResponseCouldNotBeGeneratedException;
}
